language: go
sudo: false

go:
- 1.9

before_install:
  - go get github.com/mattn/goveralls

jobs:
  include:
    - stage: compile
      script: make linux darwin
    - stage: test
      script: make coveralls

tags: true